services:
  frontend:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - ./frontend/node_modules:/opt/app/node_modules
      - ./frontend:/opt/app
    environment:
      - WDS_SOCKET_PORT=3000
    ports:
      - "3000:3000"
    networks:
        - common-network

  drivers-api:
    image: drivers-image
    environment:
      CONNECT_TO_DOCKER_DB: ${CONNECT_TO_DOCKER_DB}
      CLIENT_URL: ${CLIENT_URL}
    read_only: true
    build:
      context: ./backend
      dockerfile: Awantura.Api/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - common-network

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always
    networks:
      - common-network

networks:
  common-network:
    driver: bridge

volumes:
  sqlserver_data: